project:
  type: website

website:
  google-analytics: G-KE805TGSHC
  title: "alexbass.me"
  page-navigation: true
  comments: 
    giscus: 
      repo: acbass49/personal_quarto_site
      reactions-enabled: true
      input-position: bottom
  navbar:
    search: false
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - text: Resume
        href: files/resume.pdf
    logo: graph-up.svg
  favicon: graph-up.svg
  twitter-card:
    creator: "@acbass49"
  page-footer:
    center: 
      - text: "About Me"
        href: index.qmd
      - text: "Latest Post"
        href: posts/digital_nomad_life/index.qmd
      - text: Latest Project
        href: projects/election_model_2024/index.qmd
    right: 
      - text: "Made with Quarto & Netlify ❤️"
  site-url: "https://alexbass.me"
  body-header: |
    <!-- 100% privacy-first analytics -->
    <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
    <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>
format:
  html:
    theme: litera
    css: styles.css
