project:
  type: website

website:
  title: "alexbass.me"
  page-navigation: true
  navbar:
    search: false
    left:
      - href: index.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - text: CV
        href: files/cv.pdf
    logo: graph-up.svg
  favicon: graph-up.svg
  twitter-card:
    creator: "@acbass49"
  page-footer:
    center: 
      - text: "About Me"
        href: index.qmd
      - text: "👉 My Latest Post 👈"
        href: posts/google_trends/index.qmd
      - text: CV
        href: files/cv.pdf
  site-url: "https://alexbass.me"
  google-analytics: "UA-194046200-1"
format:
  html:
    theme: litera
    css: styles.css
