project:
  type: website

website:
  title: "alexbass.me"
  page-navigation: true
  navbar:
    search: false
    left:
      - href: index.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - text: CV
        href: files/cv.pdf
    logo: graph-up.svg
  favicon: graph-up.svg
  twitter-card:
    creator: "@acbass49"
  page-footer:
    center: 
      - text: "About Me"
        href: index.qmd
      - text: "👉 My Latest Post 👈"
        href: posts/simple_analytics/index.qmd
      - text: CV
        href: files/cv.pdf
  site-url: "https://alexbass.me"
  body-footer: |
    <!-- 100% privacy-first analytics -->
    <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
    <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>
format:
  html:
    theme: litera
    css: styles.css
