project:
  type: website

website:
  title: "alexbass.me"
  open-graph: true
  page-navigation: true
  navbar:
    left:
      - href: about.qmd
        text: About Me
      - href: index.qmd
        text: Content
      - text: CV
        href: files/cv.pdf
    logo: graph-up.svg
  favicon: graph-up.svg
  twitter-card:
    creator: "@acbass49"
format:
  html:
    theme: litera
    css: styles.css



