project:
  type: website

website:
  title: "alexbass.me"
  page-navigation: true
  comments: 
    giscus: 
      repo: acbass49/personal_quarto_site
      reactions-enabled: true
      input-position: bottom
  navbar:
    search: false
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - text: Resume
        href: files/resume.pdf
    logo: graph-up.svg
  favicon: graph-up.svg
  twitter-card:
    creator: "@acbass49"
  page-footer:
    center: 
      - text: "About Me"
        href: index.qmd
      - text: "Latest Post"
        href: posts/election_2024/index.qmd
      - text: Latest Project
        href: projects/election_model_2024/index.qmd
  site-url: "https://alexbass.me"
  body-header: |
    <!-- 100% privacy-first analytics -->
    <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
    <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>
  body-footer: |
    <div id="mc_embed_shell">
    <link href="//cdn-images.mailchimp.com/embedcode/classic-061523.css" rel="stylesheet" type="text/css">
    <style type="text/css">
          #mc_embed_signup{background:#fff; false;clear:left; font:14px Helvetica,Arial,sans-serif; width: auto;margin: auto;font-family: "Times New Roman";}
    </style>
    <br>
    <div id="mc_embed_signup">
    <form action="https://alexbass.us9.list-manage.com/subscribe/post?u=1dfb80159002061eb81b96856&amp;id=3939803566&amp;f_id=00b4c1e0f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_self" novalidate="">
    <div id="mc_embed_signup_scroll">
    <div class="mc-field-group"><label for="mce-EMAIL">Want to be notified for new posts? Enter your email address below: <span class="asterisk">*</span></label><input type="email" name="EMAIL" class="required email" id="mce-EMAIL" required="" value=""><span id="mce-EMAIL-HELPERTEXT" class="helper_text"></span></div>
    <div id="mce-responses" class="clear foot">
    <div class="response" id="mce-error-response" style="display: none;"></div>
    <div class="response" id="mce-success-response" style="display: none;"></div>
    </div>
    <div aria-hidden="true" style="position: absolute; left: -5000px;">
          /* real people should not fill this in and expect good things - do not remove this or risk form bot signups */
    <input type="text" name="b_1dfb80159002061eb81b96856_3939803566" tabindex="-1" value="">
    </div>
    <div class="optionalParent">
    <div class="clear foot">
    <input type="submit" name="subscribe" id="mc-embedded-subscribe" class="button" value="Subscribe">
    </div>
    </div>
    </div>
    </form>
    </div>
    </div>
format:
  html:
    theme: litera
    css: styles.css
