name: 'Update Stream Graphs'

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"
jobs:
  quarto-rerender:
    runs-on: ubuntu-latest
    steps:
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          token: ${{ secrets.SECRETS }}
      - name: clone personal site
        run: |
          git config --global user.name "github_actions"
          git config --global user.email "acbass49@gmail.com"
          git clone "https://github.com/acbass49/personal_quarto_site.git"
        shell: bash
      - name: re-render site
        run: |
          cd personal_quarto_site
          quarto render
        shell: bash
      - name: push new version
        run: |
          cd personal_quarto_site
          git add .
          git commit -m "StreamGraph Update"
          git push
        shell: bash
#git remote set-url origin https://x-access-token:${{ secrets.SECRETS }}@github.com:acbass49/personal_quarto_site.git
