name: Update Quarto Graph

on:
  schedule:
    - cron: "1/5 * * * *" # Every Saturday at 11am UTC 0 11 * * 6

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  Update_stream_graph:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.SECRETS }}
      
      # execute Rscript
      - name: Running script
        run: |
          gh release download --repo github.com/quarto-dev/quarto-cli --pattern ${{ format('*{0}', env.BUNDLE_EXT) }}
            version=$(curl https://quarto.org/docs/download/_download.json | jq -r '.version')
            echo "version=${version}" >> $GITHUB_OUTPUT
          sudo apt install ./$installer
          git config --global user.name "${{ acbass49 }}"
          git config --global user.email "acbass49@gmail.com"
          git clone "https://github.com/acbass49/personal_quarto_site.git"
          cd personal_quarto_site
          quarto render
          git add .
          git commit -m "StreamGraph Update"
          git push
        shell: bash
