name: Update Quarto Graph

on:
  schedule:
    - cron: "1/5 * * * *"

jobs:
  Update_stream_graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.SECRETS }}
      - name: 'Install Linux'
        run: echo "BUNDLE_EXT=linux-amd64.deb" >> $GITHUB_ENV
        shell: bash
      - name: 'Download Quarto'
        run: |
          gh release download --repo github.com/quarto-dev/quarto-cli --pattern ${{ format('*{0}', env.BUNDLE_EXT) }}
          version=$(curl https://quarto.org/docs/download/_download.json | jq -r '.version')
          echo "version=${version}" >> $GITHUB_OUTPUT
        shell: bash
      - name: 'Install Quarto'
        run: sudo apt install ./$installer
        shell: bash
      - name: Update Website
        run: |
          git config --global user.name "${{ secrets.USR }}"
          git config --global user.email "acbass49@gmail.com"
          git clone "https://github.com/acbass49/personal_quarto_site.git"
          cd personal_quarto_site
          quarto render
          git add .
          git commit -m "StreamGraph Update"
          git push
        shell: bash
