name: 'Update Stream Graphs'

on:
  schedule:
    - cron: "1/5 * * * *"
jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: quarto-dev/quarto-actions/setup@v2
        env: 
          CI_COMMIT_AUTHOR: acbass49
        with:
          token: ${{ secrets.SECRETS }}
      - run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - run: echo "${{ secrets.USR }}"
      - run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "acbass49@gmail.com"
          git clone "https://github.com/acbass49/personal_quarto_site.git"
          cd personal_quarto_site
          quarto render
          git add .
          git commit -m "StreamGraph Update ${{ steps.date.outputs.date }}"
          git push
        shell: bash
